name: Deploy Desafio Vaga Simplify

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build project
        run: mvn clean install -DskipTests
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build docker image
        run: docker build -t eliasfernandescout/desafiosimplify .
      - name: Push image docker
        run: docker push eliasfernandescout/desafiosimplify

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Add user to docker group
        run: sudo usermod -aG docker $(whoami)
      - name: Pull image from docker hub
        run: sudo docker pull eliasfernandescout/desafiosimplify:latest
      - name: Remove docker container
        run: sudo docker rm -f desafiosimplify
      - name: Run docker container
        run: sudo docker run -d -p 8080:8080 --name desafiosimplify eliasfernandescout/desafiosimplify
      - name: Remove old docker image
        run: sudo docker image prune -f